//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsAplikacija
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WinFormsAplikacijaDbEntities1 : DbContext
    {
        public WinFormsAplikacijaDbEntities1()
            : base("name=WinFormsAplikacijaDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClanoviObitelji> ClanoviObitelji { get; set; }
        public virtual DbSet<Djelatnici> Djelatnici { get; set; }
    }
}
