//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsAplikacija
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClanoviObitelji
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<System.DateTime> DatumRodjena { get; set; }
        public string Spol { get; set; }
        public Nullable<int> DjelatnikId { get; set; }
    
        public virtual Djelatnici Djelatnici { get; set; }
    }
}
